parameters:
    interactify_integration.activities_provider.class:  Interactify\Bundle\IntegrationBundle\Provider\ActivityProvider
    interactify_integration.entities_provider.class: Interactify\Bundle\IntegrationBundle\Provider\EntityProvider

services:
    interactify_integration.activities_provider:
        class: %interactify_integration.activities_provider.class%
        arguments:
            - '@oro_activity.manager'
            - '@doctrine.orm.entity_manager'
    interactify_integration.entities_provider:
        class: %interactify_integration.entities_provider.class%
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@service_container'

#    interactify_integration.example:
#        class: Interactify\Bundle\IntegrationBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
